### ISSUE TITLE
Any plans to do a new release?

### ISSUE THREAD

**Issue by nanodocumet** [purplepixie/phpdns#18]
Hi there, wondering if there are plans to do a release with latest changes. The latest version is `2.0.5` which is more than 7 years old and there is some new code has been added since then. I am personally interested in this [merged PR](https://github.com/purplepixie/phpdns/pull/16) and will prefer to avoid using `dev-master` (using `"purplepixie/phpdns": "2.0.*@dev"` works but releasing a new version might be still worth it)

**Comment by purplepixie** [comment]
Hello. Yes there are plans, just finding time. I'll prioritise this though and try and get testing completed to roll out a new version.

**Comment by sveneld** [comment]
Hi.
Any news?

**Comment by purplepixie** [comment]
2.1.0 has just dropped which includes all the latest updates.
